# Generated by Django 5.1 on 2025-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorverification',
            name='answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='creatorverification',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='问题'),
        ),
    ]
