# Generated by Django 5.1 on 2025-12-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_creatorverification_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="邮箱已验证"),
        ),
    ]
