# Generated by Django 5.1 on 2025-11-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0002_initial'),
        ('podcasts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='follow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='podcasts.show', verbose_name='播客节目'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='podcasts.episode', verbose_name='单集'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='podcasts.episode', verbose_name='单集'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['episode', '-created_at'], name='comments_episode_e6dd39_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['user', '-created_at'], name='follows_user_id_833461_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'show')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'episode')},
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['user', '-last_played_at'], name='play_histor_user_id_65640f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playhistory',
            unique_together={('user', 'episode')},
        ),
    ]
