# Generated by Django 5.1 on 2025-11-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='搜索关键词')),
                ('search_count', models.IntegerField(default=1, verbose_name='搜索次数')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='最后搜索时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '热门搜索',
                'verbose_name_plural': '热门搜索',
                'db_table': 'popular_search',
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-search_count', '-last_searched_at'], name='popular_sea_search__c4cf9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='搜索关键词')),
                ('session_key', models.CharField(blank=True, help_text='未登录用户使用', max_length=100, null=True, verbose_name='会话标识')),
                ('results_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['session_key', '-created_at'], name='search_hist_session_d27e15_idx'), models.Index(fields=['query'], name='search_hist_query_69a772_idx')],
            },
        ),
    ]
