# Generated by Django 5.1 on 2025-11-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, help_text='Element Plus 图标名', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#ff513b', help_text='马卡龙配色', max_length=7, verbose_name='颜色')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL标识')),
                ('description', models.TextField(verbose_name='描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='episode_covers/%Y/%m/', verbose_name='封面')),
                ('audio_file', models.FileField(upload_to='episodes/%Y/%m/', verbose_name='音频文件')),
                ('duration', models.IntegerField(default=0, help_text='秒数', verbose_name='时长')),
                ('file_size', models.BigIntegerField(default=0, help_text='字节', verbose_name='文件大小')),
                ('episode_number', models.IntegerField(blank=True, null=True, verbose_name='集数')),
                ('season_number', models.IntegerField(blank=True, null=True, verbose_name='季数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('published', '已发布'), ('failed', '处理失败')], default='draft', max_length=20, verbose_name='状态')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '播客单集',
                'verbose_name_plural': '播客单集',
                'db_table': 'episodes',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(verbose_name='描述')),
                ('cover', models.ImageField(upload_to='covers/%Y/%m/', verbose_name='封面')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选')),
                ('episodes_count', models.IntegerField(default=0, verbose_name='单集数')),
                ('followers_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('total_plays', models.IntegerField(default=0, verbose_name='总播放')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='podcasts.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '播客节目',
                'verbose_name_plural': '播客节目',
                'db_table': 'shows',
                'ordering': ['-created_at'],
            },
        ),
    ]
