# Generated by Django 5.1 on 2025-11-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.show', verbose_name='播客节目'),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shows', to='podcasts.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['show', '-published_at'], name='episodes_show_id_dc3770_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['status', '-published_at'], name='episodes_status_f91399_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('show', 'slug')},
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-created_at'], name='shows_created_4658d6_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-total_plays'], name='shows_total_p_2969d1_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['is_featured', '-followers_count'], name='shows_is_feat_a000c9_idx'),
        ),
    ]
