# Generated by Django 5.1 on 2025-11-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='album_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='专辑名'),
        ),
        migrations.AddField(
            model_name='episode',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='艺术家'),
        ),
        migrations.AddField(
            model_name='episode',
            name='genre',
            field=models.CharField(blank=True, help_text='如：流行、摇滚、古典等', max_length=100, null=True, verbose_name='流派'),
        ),
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='发行日期'),
        ),
        migrations.AddField(
            model_name='show',
            name='content_type',
            field=models.CharField(choices=[('podcast', '播客'), ('music', '音乐')], db_index=True, default='podcast', max_length=20, verbose_name='内容类型'),
        ),
    ]
