# Generated by Django 5.1 on 2025-11-20 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_episode_album_name_episode_artist_episode_genre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='会话标题')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('chat_history', models.JSONField(default=list, verbose_name='对话历史')),
                ('current_script', models.TextField(blank=True, help_text='Markdown格式，包含【角色名】标签', verbose_name='当前脚本')),
                ('script_versions', models.JSONField(default=list, verbose_name='脚本版本历史')),
                ('voice_config', models.JSONField(blank=True, default=dict, verbose_name='音色配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
                ('episode', models.OneToOneField(blank=True, help_text='生成音频后关联的Episode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_session', to='podcasts.episode', verbose_name='生成的单集')),
                ('show', models.ForeignKey(blank=True, help_text='可选，如果已选择节目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_sessions', to='podcasts.show', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': 'AI脚本会话',
                'verbose_name_plural': 'AI脚本会话',
                'db_table': 'script_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='script_references/%Y/%m/', verbose_name='文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('txt', '文本文件'), ('pdf', 'PDF文档'), ('md', 'Markdown文档'), ('docx', 'Word文档')], max_length=10, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(help_text='字节', verbose_name='文件大小')),
                ('extracted_text', models.TextField(blank=True, help_text='从文件中提取的纯文本内容', verbose_name='提取的文本')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='podcasts.scriptsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '参考文件',
                'verbose_name_plural': '参考文件',
                'db_table': 'uploaded_references',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
