# Generated by Django 5.1 on 2025-11-26 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_scriptsession_uploadedreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='当可见性为"仅受邀用户"时生效', related_name='shared_episodes', to=settings.AUTH_USER_MODEL, verbose_name='共享给用户'),
        ),
        migrations.AddField(
            model_name='episode',
            name='visibility',
            field=models.CharField(choices=[('inherit', '继承节目设置'), ('public', '公开'), ('unlisted', '不公开列出（仅链接可访问）'), ('followers', '仅关注者'), ('private', '私有'), ('shared', '仅受邀用户')], db_index=True, default='inherit', help_text='inherit 表示继承节目的可见性设置', max_length=20, verbose_name='可见性'),
        ),
        migrations.AddField(
            model_name='show',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='当可见性为"仅受邀用户"时生效', related_name='shared_shows', to=settings.AUTH_USER_MODEL, verbose_name='共享给用户'),
        ),
        migrations.AddField(
            model_name='show',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('unlisted', '不公开列出（仅链接可访问）'), ('followers', '仅关注者'), ('private', '私有'), ('shared', '仅受邀用户')], db_index=True, default='public', help_text='控制谁可以看到这个节目', max_length=20, verbose_name='可见性'),
        ),
    ]
