# Generated by Django 5.1 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_add_visibility_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='script',
            field=models.TextField(blank=True, help_text='Markdown格式，包含【角色名】标签，创作者可编辑以调整TTS发音', verbose_name='脚本'),
        ),
    ]
