# Generated by Django 5.1 on 2025-12-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_episode_dialogue_episode_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(blank=True, help_text='Debate/Conference模式可为空，发布音频时再关联', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.show', verbose_name='播客节目'),
        ),
    ]
