# Generated by Django 5.1 on 2026-02-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_alter_episode_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='generation_error',
            field=models.TextField(blank=True, default='', verbose_name='生成错误信息'),
        ),
        migrations.AddField(
            model_name='episode',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成元数据'),
        ),
        migrations.AddField(
            model_name='episode',
            name='generation_stage',
            field=models.CharField(choices=[('queued', '排队中'), ('source_fetching', '抓取中'), ('script_generating', '写稿中'), ('audio_generating', '音频生成中'), ('cover_generating', '封面生成中'), ('completed', '完成'), ('failed', '失败')], db_index=True, default='queued', max_length=32, verbose_name='生成阶段'),
        ),
    ]
