# Generated by Django 5.1 on 2026-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_alter_episode_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreference',
            name='github_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GitHub用户名/组织'),
        ),
        migrations.AddField(
            model_name='uploadedreference',
            name='github_path',
            field=models.CharField(blank=True, default='README.md', max_length=500, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='uploadedreference',
            name='github_ref',
            field=models.CharField(blank=True, default='main', max_length=100, null=True, verbose_name='分支/标签'),
        ),
        migrations.AddField(
            model_name='uploadedreference',
            name='github_repo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库名'),
        ),
        migrations.AddField(
            model_name='uploadedreference',
            name='source_type',
            field=models.CharField(choices=[('upload', '用户上传'), ('github', 'GitHub导入')], db_index=True, default='upload', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='uploadedreference',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='来源URL'),
        ),
    ]
