# Generated by Django 5.1 on 2026-02-07

from django.db import migrations


LEGACY_DEFAULT_SHOW_TITLES = {"我的音频", "我的频道"}
DEFAULT_SHOW_SLUG_PREFIX = "audio-workbench-"


def rename_legacy_default_show_titles(apps, schema_editor):
    Show = apps.get_model("podcasts", "Show")
    User = apps.get_model("users", "User")

    legacy_shows = list(
        Show.objects.filter(
            slug__startswith=DEFAULT_SHOW_SLUG_PREFIX,
            title__in=LEGACY_DEFAULT_SHOW_TITLES,
        ).only("id", "creator_id", "title")
    )

    if not legacy_shows:
        return

    creator_ids = {show.creator_id for show in legacy_shows}
    usernames = dict(
        User.objects.filter(id__in=creator_ids).values_list("id", "username")
    )

    to_update = []
    for show in legacy_shows:
        username = (usernames.get(show.creator_id) or "").strip()
        if not username:
            username = f"用户{show.creator_id}"
        target_title = f"{username}的频道"[:255]
        if show.title != target_title:
            show.title = target_title
            to_update.append(show)

    if to_update:
        Show.objects.bulk_update(to_update, ["title"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_episode_generation_error_episode_generation_meta_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_legacy_default_show_titles, migrations.RunPython.noop),
    ]
