# Generated by Django 5.1 on 2026-02-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_uploadedreference_github_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedreference',
            name='github_owner',
        ),
        migrations.RemoveField(
            model_name='uploadedreference',
            name='github_path',
        ),
        migrations.RemoveField(
            model_name='uploadedreference',
            name='github_ref',
        ),
        migrations.RemoveField(
            model_name='uploadedreference',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='uploadedreference',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='uploadedreference',
            name='source_url',
        ),
    ]
