# Generated by Django 5.1 on 2026-02-07 10:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_rename_legacy_default_show_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='列表名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RSS 列表',
                'verbose_name_plural': 'RSS 列表',
                'db_table': 'rss_lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RSSSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='规则名')),
                ('template', models.CharField(default='news_flash', max_length=32, verbose_name='模板')),
                ('max_items', models.PositiveSmallIntegerField(default=8, verbose_name='抓取条数')),
                ('deduplicate', models.BooleanField(default=True, verbose_name='去重')),
                ('sort_by', models.CharField(choices=[('latest', 'latest'), ('oldest', 'oldest'), ('title', 'title')], default='latest', max_length=12, verbose_name='排序')),
                ('host_name', models.CharField(blank=True, default='', max_length=64, verbose_name='主持名')),
                ('guest_name', models.CharField(blank=True, default='', max_length=64, verbose_name='嘉宾名')),
                ('host_voice_id', models.CharField(blank=True, default='', max_length=128, verbose_name='主持音色ID')),
                ('guest_voice_id', models.CharField(blank=True, default='', max_length=128, verbose_name='嘉宾音色ID')),
                ('timezone_name', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区')),
                ('run_time', models.TimeField(default=datetime.time(8, 0), verbose_name='执行时间')),
                ('frequency', models.CharField(choices=[('daily', '每天'), ('weekly', '每周')], default='daily', max_length=12, verbose_name='频率')),
                ('week_days', models.JSONField(blank=True, default=list, help_text='0-6, 周一到周日', verbose_name='每周执行日')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次执行时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_status', models.CharField(choices=[('idle', '空闲'), ('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='idle', max_length=20, verbose_name='最近状态')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_schedules', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('rss_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='podcasts.rsslist', verbose_name='RSS 列表')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_schedules', to='podcasts.show', verbose_name='目标频道')),
            ],
            options={
                'verbose_name': 'RSS 定时规则',
                'verbose_name_plural': 'RSS 定时规则',
                'db_table': 'rss_schedules',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RSSRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=20, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('auto', '自动触发'), ('manual', '手动触发')], default='auto', max_length=20, verbose_name='触发方式')),
                ('message', models.TextField(blank=True, verbose_name='说明')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('item_count', models.IntegerField(default=0, verbose_name='条目数')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_runs', to='podcasts.episode', verbose_name='生成单集')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='podcasts.rssschedule', verbose_name='规则')),
            ],
            options={
                'verbose_name': 'RSS 运行记录',
                'verbose_name_plural': 'RSS 运行记录',
                'db_table': 'rss_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('url', models.URLField(max_length=500, verbose_name='RSS 地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_sources', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RSS 源',
                'verbose_name_plural': 'RSS 源',
                'db_table': 'rss_sources',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='rsslist',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='rss_lists', to='podcasts.rsssource', verbose_name='源'),
        ),
        migrations.AddIndex(
            model_name='rssschedule',
            index=models.Index(fields=['creator', 'is_active'], name='rss_schedul_creator_29eecd_idx'),
        ),
        migrations.AddIndex(
            model_name='rssschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='rss_schedul_is_acti_2a182e_idx'),
        ),
        migrations.AddIndex(
            model_name='rssschedule',
            index=models.Index(fields=['-updated_at'], name='rss_schedul_updated_bfe7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='rssrun',
            index=models.Index(fields=['schedule', '-started_at'], name='rss_runs_schedul_ebc46f_idx'),
        ),
        migrations.AddIndex(
            model_name='rssrun',
            index=models.Index(fields=['status', '-started_at'], name='rss_runs_status_df1fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='rsssource',
            index=models.Index(fields=['creator', 'is_active'], name='rss_sources_creator_6a2715_idx'),
        ),
        migrations.AddIndex(
            model_name='rsssource',
            index=models.Index(fields=['-updated_at'], name='rss_sources_updated_374702_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rsssource',
            unique_together={('creator', 'url')},
        ),
        migrations.AddIndex(
            model_name='rsslist',
            index=models.Index(fields=['creator', 'is_active'], name='rss_lists_creator_37b83e_idx'),
        ),
        migrations.AddIndex(
            model_name='rsslist',
            index=models.Index(fields=['-updated_at'], name='rss_lists_updated_e833dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rsslist',
            unique_together={('creator', 'name')},
        ),
    ]
