# Generated by Django 5.1 on 2026-02-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_episode_generation_error_episode_generation_meta_and_more'),
        ('podcasts', '0010_remove_uploadedreference_github_owner_and_more'),
    ]

    operations = [
    ]
