# Generated by Django 5.1 on 2026-02-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_rename_legacy_default_show_titles'),
        ('podcasts', '0011_merge_20260207_1805'),
    ]

    operations = [
    ]
