# Generated by Django 5.1 on 2026-02-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_rsslist_rssschedule_rssrun_rsssource_rsslist_sources_and_more'),
        ('podcasts', '0012_merge_20260207_1814'),
    ]

    operations = [
    ]
